apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp
spec:
  selector:
    matchLabels:
      app: sampleapp
  replicas: 3
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
      - name: sampleapp
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
